apiVersion: v1
kind: Pod
metadata:
  labels:
    run: web-yaml
  name: web-yaml
spec:
  containers:
  - image: nginx
    name: web-yaml
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
